gcpProjectId: ""
gcpProjectNumber: ""

projectIamRoles: []

topics: []

subscriptions: []

buckets: []

databases: []

serviceName: ""
image:
  repository: ""
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: Always

imagePullSecrets:
  - name: registry-credentials

serviceAccount:
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
# fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
#  className: nginx
#  annotations: { }
#  enableTls: true
#  hosts:
#    - host: api.dev.lease-seven.dev
#      paths:
#        - path: /
#          pathType: Prefix

env: []

resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

livenessProbe: {}
readinessProbe: {}

## INFO ##
# - replicaCount is ignored if autoscaling is enabled
##########
replicaCount: 1
autoscaling:
  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
#  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

initContainers: []
# - name: init-container
#   image: busybox:latest
#   command: ['sh', '-c', 'echo "Init container running"']
